name: Sync Git Repos
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # once a day

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Initialising
      env:
           GitHubAccessToken: ${{ secrets.GitHubAccessToken }}
           GitLabAccessToken: ${{ secrets.GitLabAccessToken }}
      run: |
           bash scripts/setup.sh
           echo '{"GitHubAccessToken": "'"$GitHubAccessToken"'", "GitLabAccessToken": "'"$GitLabAccessToken"'"}' > config.json

    - name: Sync Process
      run: python3 gitpush.py
